name: activ_lock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  google_mlkit_pose_detection: ^0.12.0
  camera: ^0.10.5
  shared_preferences: ^2.2.2
  flutter_background_service: ^5.0.0
  installed_apps: ^2.1.0
  permission_handler: ^11.0.0
  usage_stats: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/app_icon.png"